### ISSUE TITLE
Add support for NGSI-LD tenants

### ISSUE THREAD

**Issue by bobeal** [stellio-hub/stellio-context-broker#680]
**General principles**

Two main points are to be considered:
- Authentication and authorization
- Database routing

For the first version, automatic creation of tenants will be not be supported, at least for production deployments. Indeed, on the fly creation of a database schema is possible without a lot of effort. However, it is more complex on the authentication side where a new realm must be created in Keycloak... with at least an user having admin rights in the context broker (and this cannot be automated).

**Tasks**

- [x] NGSILD-Tenant header in requests
- [x] NGSILD-Tenant header in responses
- [x] Business rules (URI format, `NonexistentTenant`,...)
- [x] Dynamic DB connection according to current tenant
- [x] Automatic DB migration on all known tenants
- [x] Authentication in respective realm in Keycloak
- [x] Integrate non shareable pieces of code in subscription once validated in search
- [x] Specific parts for subscription (tenant info in notifications)
- [ ] Document how to manage tenants (create, delete)

**Resources**

***Auth(z)***

* https://docs.spring.io/spring-security/reference/reactive/oauth2/resource-server/multitenancy.html
* https://github.com/keycloak/keycloak-quickstarts/tree/latest/app-authz-springboot-multitenancy

***Database routing***

* https://docs.spring.io/spring-data/r2dbc/docs/current/reference/html/#r2dbc.multiple-databases (also have a look at `AbstractR2dbcConfiguration`):
  * The commit that introduced the feature: https://github.com/spring-projects/spring-data-r2dbc/commit/e3aae619f416645314c9f9bd0ce5ddfa874a30b9
  * The tests for some examples: https://github.com/spring-projects/spring-data-r2dbc/blob/7ec3d28b17ef4c4a6c77b355c777cccf9519cb10/src/test/java/org/springframework/data/r2dbc/connectionfactory/lookup/AbstractRoutingConnectionFactoryUnitTests.java#L39
  * https://github.com/hantsy/spring-puzzles/tree/master/multi-tenancy-r2dbc is a good example to start with (other examples often rely on thread, which will not work in a reactive application)
* How to create DB schema for a new tenant?
* How to apply Flyway migrations on all databases?
  * Need to know all the tenants at startup to loop through them and apply the migrations (https://grobmeier.solutions/spring-multitenancy-switch-database-at-runtime.html has some notes about this)

**Comment by bobeal** [comment]
see https://docs.spring.io/spring-security/reference/reactive/oauth2/resource-server/multitenancy.html
